"""Generate C headers and CMSIS-SVD from detected registers.

Heuristic extraction is imperfect, so the output is clearly marked "verify
against the datasheet". Field bit positions are always emitted; register address
defines / SVD entries are only emitted when an address was detected (the
medium/large LLM tiers extract addresses far more reliably than the small tier).
"""
from __future__ import annotations

import html
import re
from typing import List, Optional, Tuple


def _ident(s: str, upper: bool = True) -> str:
    s = re.sub(r"[^A-Za-z0-9_]", "_", (s or "").strip())
    s = re.sub(r"_+", "_", s).strip("_") or "X"
    if s[0].isdigit():
        s = "_" + s
    return s.upper() if upper else s


def _bits(s: str) -> Optional[Tuple[int, int]]:
    """Return (lo_offset, width) for a bits spec like '7', '7:0', '5-3'."""
    s = (s or "").replace(" ", "")
    m = re.match(r"^(\d+)[:\-–](\d+)$", s)
    if m:
        a, b = int(m.group(1)), int(m.group(2))
        return min(a, b), abs(a - b) + 1
    if s.isdigit():
        return int(s), 1
    return None


def _addr(s: str) -> Optional[str]:
    s = (s or "").strip()
    if re.match(r"^0[xX][0-9A-Fa-f]+$", s):
        return "0x" + s[2:].upper()
    if re.match(r"^[0-9A-Fa-f]+[hH]$", s):
        return "0x" + s[:-1].upper()
    if s.isdigit():
        return hex(int(s)).upper().replace("X", "x")
    return None


def build_c_header(reg_groups: List[dict], device: str, source: str) -> str:
    guard = _ident(device) + "_H"
    out = [
        f"/* {device} register definitions — generated by datasheet-wiki from {source}.",
        " * Heuristic extraction: VERIFY every address, width and bit position against",
        " * the datasheet before using in production. */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <stdint.h>",
        "",
    ]
    any_field = False
    for g in reg_groups:
        title = g.get("title") or ""
        out.append(f"/* ===== {title} ===== */")
        for r in g.get("registers", []):
            reg = _ident(r.name)
            addr = _addr(getattr(r, "address", "") or (r.get("address") if isinstance(r, dict) else ""))
            desc = (getattr(r, "description", "") or "").strip()
            out.append(f"/* {reg}{(' — ' + desc) if desc else ''} */")
            if addr:
                out.append(f"#define {reg}_ADDR        ({addr}u)")
                out.append(f"#define {reg}            (*(volatile uint32_t *){addr}u)")
            for f in getattr(r, "fields", []) or []:
                bw = _bits(f.bits)
                if not bw:
                    continue
                any_field = True
                lo, width = bw
                fld = _ident(f.name)
                mask = (1 << width) - 1
                out.append(f"#define {reg}_{fld}_Pos    ({lo}u)")
                out.append(f"#define {reg}_{fld}_Msk    (0x{mask:X}u << {reg}_{fld}_Pos)")
            out.append("")
    out.append(f"#endif /* {guard} */")
    if not any_field and not any(g.get("registers") for g in reg_groups):
        return ""  # nothing useful
    return "\n".join(out) + "\n"


def build_svd(reg_groups: List[dict], device: str, source: str) -> Optional[str]:
    """Minimal CMSIS-SVD. Only registers with a detected address are included;
    returns None if none qualify (SVD requires addresses)."""
    peripherals = []
    for g in reg_groups:
        regs_xml = []
        for r in g.get("registers", []):
            addr = _addr(getattr(r, "address", "") or "")
            if not addr:
                continue
            fields_xml = []
            for f in getattr(r, "fields", []) or []:
                bw = _bits(f.bits)
                if not bw:
                    continue
                lo, width = bw
                acc = _svd_access(getattr(f, "access", ""))
                fields_xml.append(
                    "          <field><name>{n}</name><bitOffset>{o}</bitOffset>"
                    "<bitWidth>{w}</bitWidth>{a}</field>".format(
                        n=html.escape(_ident(f.name, upper=False)), o=lo, w=width,
                        a=(f"<access>{acc}</access>" if acc else ""),
                    )
                )
            regs_xml.append(
                "        <register><name>{n}</name><addressOffset>{a}</addressOffset>"
                "<size>32</size>{f}</register>".format(
                    n=html.escape(_ident(r.name, upper=False)), a=addr,
                    f=("\n        <fields>\n" + "\n".join(fields_xml) + "\n        </fields>\n      " if fields_xml else ""),
                )
            )
        if regs_xml:
            peripherals.append(
                "    <peripheral>\n      <name>{n}</name>\n"
                "      <baseAddress>0x0</baseAddress>\n"
                "      <registers>\n{r}\n      </registers>\n    </peripheral>".format(
                    n=html.escape(_ident(g.get("title") or "PERIPH", upper=False)),
                    r="\n".join(regs_xml),
                )
            )
    if not peripherals:
        return None
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Generated by datasheet-wiki from {src}. Heuristic — verify against the datasheet. -->\n"
        '<device schemaVersion="1.3" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" '
        'xs:noNamespaceSchemaLocation="CMSIS-SVD.xsd">\n'
        "  <name>{dev}</name>\n  <version>1.0</version>\n"
        "  <description>{dev} (generated)</description>\n"
        "  <addressUnitBits>8</addressUnitBits>\n  <width>32</width>\n  <size>32</size>\n"
        "  <peripherals>\n{periphs}\n  </peripherals>\n</device>\n"
    ).format(src=html.escape(source), dev=html.escape(_ident(device, upper=False)), periphs="\n".join(peripherals))


def _svd_access(a: str) -> str:
    a = (a or "").lower().replace(" ", "")
    if "r/w" in a or "rw" in a:
        return "read-write"
    if a in ("r", "ro", "read"):
        return "read-only"
    if a in ("w", "wo", "write"):
        return "write-only"
    return ""
